### ISSUE TITLE
ERROR: internal error in parser, try to reduce ARG_MAX

### ISSUE THREAD

**Issue by amai2012** [lvc/japi-compliance-checker#37]
Version 2.0 triggers a "ERROR: internal error in parser, try to reduce ARG_MAX" message.
1.8 works fine on the very same data. I've found issue #7 but that is quite old.

My environment is Windows 7, JDK7. I specify two XML as input as well as a library name. Here is some debug output from perl. -debug for the tool didn't show anything new.

```
[exec] main::mergeTypes() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 881.
     [exec] main::mergeTypes() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 1354.
     [exec] main::findMethod() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 1490.
     [exec] main::getModules() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 50.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 55.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 56.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 57.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 58.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 59.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 60.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 61.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 62.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 63.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 64.
     [exec] main::errMsg() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 147.
     [exec] main::errMsg() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 158.
     [exec] Preparing, please wait ...
     [exec] main::getArgMax() called too early to check prototype at c:/projects/japi-compliance/download/modules/Internals/Utils.pm line 23.
     [exec] Use of uninitialized value $In::Opt{"OS"} in string eq at c:/projects/japi-compliance/download/modules/Internals/Utils.pm line 53.
     [exec] main::getBaseType() called too early to check prototype at c:/projects/japi-compliance/download/modules/Internals/TypeAttr.pm line 69.
     [exec] Use of uninitialized value $Java in hash element at c:/projects/japi-compliance/download/modules/Internals/SysFiles.pm line 150.
     [exec] Use of uninitialized value $Java in hash element at c:/projects/japi-compliance/download/modules/Internals/SysFiles.pm line 154.
     [exec] main::readArchive() called too early to check prototype at c:/projects/japi-compliance/download/modules/Internals/APIDump.pm line 179.
     [exec] main::registerType() called too early to check prototype at c:/projects/japi-compliance/download/modules/Internals/APIDump.pm line 830.
     [exec] Use of uninitialized value $In::Opt{"TargetLibraryName"} in concatenation (.) or string at c:/projects/japi-compliance/download/modules/Internals/Logging.pm line 78.
     [exec] Use of uninitialized value $Bin in hash element at c:/projects/japi-compliance/download/modules/Internals/SysFiles.pm line 150.
     [exec] Use of uninitialized value $Bin in hash element at c:/projects/japi-compliance/download/modules/Internals/SysFiles.pm line 154.
     [exec] Using Java 1.7.0_79
     [exec] Reading classes 5_35 ...
     [exec] Argument "" isn't numeric in numeric ne (!=) at c:/projects/japi-compliance/download/modules/Internals/Utils.pm line 110.
     [exec] Can't spawn "cmd.exe": No such file or directory at c:/projects/japi-compliance/download/modules/Internals/APIDump.pm line 324.
     [exec] ERROR: internal error in parser, try to reduce ARG_MAX
```

**Comment by lvc** [comment]
Hi,

Please run the tool with the -test option and post the output here:

    japi-compliance-checker -test

Thank you.

**Comment by amai2012** [comment]
Script is being run from within an ant script - just to explain the format.
```
check:
     [exec] main::mergeTypes() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 881.
     [exec] main::mergeTypes() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 1354.
     [exec] main::findMethod() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 1490.
     [exec] main::getModules() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 50.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 55.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 56.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 57.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 58.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 59.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 60.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 61.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 62.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 63.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 64.
     [exec] main::errMsg() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 147.
     [exec] main::errMsg() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker line 158.
     [exec] main::getArgMax() called too early to check prototype at c:/projects/japi-compliance/download/modules/Internals/Utils.pm line 23.
     [exec] Use of uninitialized value $In::Opt{"OS"} in string eq at c:/projects/japi-compliance/download/modules/Internals/Utils.pm line 53.
     [exec] main::getBaseType() called too early to check prototype at c:/projects/japi-compliance/download/modules/Internals/TypeAttr.pm line 69.
     [exec] Using Java 1.7.0_79
     [exec] 
     [exec] Verifying detectable Java library changes
     [exec] Creating test library ...
     [exec] Argument "" isn't numeric in numeric ne (!=) at c:/projects/japi-compliance/download/modules/Internals/Utils.pm line 110.
     [exec] Argument "" isn't numeric in numeric ne (!=) at c:/projects/japi-compliance/download/modules/Internals/Utils.pm line 110.
     [exec] MethodBecameNonDefault.java:3: error: illegal start of type
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]         ^
     [exec] MethodBecameNonDefault.java:3: error: = expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                 ^
     [exec] MethodBecameNonDefault.java:3: error: ';' expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                        ^
     [exec] MethodBecameNonDefault.java:3: error: illegal start of type
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                   ^
     [exec] MethodBecameNonDefault.java:3: error: = expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                            ^
     [exec] MethodBecameNonDefault.java:3: error: illegal start of type
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                 ^
     [exec] MethodBecameNonDefault.java:3: error: <identifier> expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                  ^
     [exec] MethodBecameNonDefault.java:3: error: = expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                     ^
     [exec] MethodBecameNonDefault.java:3: error: ';' expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                           ^
     [exec] MethodBecameNonDefault.java:4: error: class, interface, or enum expected
     [exec]     }
     [exec]     ^
     [exec] 10 errors
     [exec] ERROR: can't compile classes v.1
```

**Comment by lvc** [comment]
The issue has been fixed by the commit c681d9ee593d0b4825b123ffec49abe3d13981c1.

Please download and check latest source code.

Thank you!

**Comment by amai2012** [comment]
Unfortunately I still get almost the same error messages:
~~~~
check:
     [exec] main::mergeTypes() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 881.
     [exec] main::mergeTypes() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 1354.
     [exec] main::findMethod() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 1490.
     [exec] main::getModules() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 50.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 55.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 56.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 57.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 58.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 59.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 60.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 61.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 62.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 63.
     [exec] main::loadModule() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker
 line 64.
     [exec] main::errMsg() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker lin
e 147.
     [exec] main::errMsg() called too early to check prototype at c:\projects\japi-compliance\download\japi-compliance-checker lin
e 158.
     [exec] main::getBaseType() called too early to check prototype at c:/projects/japi-compliance/download/modules/Internals/Type
Attr.pm line 69.
     [exec] Using Java 1.7.0_79
     [exec]
     [exec] Verifying detectable Java library changes
     [exec] Creating test library ...
     [exec] Use of uninitialized value $MaxDepth in numeric ne (!=) at c:/projects/japi-compliance/download/modules/Internals/Util
s.pm line 152.
     [exec] Use of uninitialized value $MaxDepth in numeric ne (!=) at c:/projects/japi-compliance/download/modules/Internals/Util
s.pm line 152.
     [exec] MethodBecameNonDefault.java:3: error: illegal start of type
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]         ^
     [exec] MethodBecameNonDefault.java:3: error: = expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                 ^
     [exec] MethodBecameNonDefault.java:3: error: ';' expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                        ^
     [exec] MethodBecameNonDefault.java:3: error: illegal start of type
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                   ^
     [exec] MethodBecameNonDefault.java:3: error: = expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                            ^
     [exec] MethodBecameNonDefault.java:3: error: illegal start of type
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                 ^
     [exec] MethodBecameNonDefault.java:3: error: <identifier> expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                  ^
     [exec] MethodBecameNonDefault.java:3: error: = expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                     ^
     [exec] MethodBecameNonDefault.java:3: error: ';' expected
     [exec]         default Integer someMethod(Integer param) { return 0; }
     [exec]                                                           ^
     [exec] MethodBecameNonDefault.java:4: error: class, interface, or enum expected
     [exec]     }
     [exec]     ^
     [exec] 10 errors
     [exec] ERROR: can't compile classes v.1
     [exec] Result: 2
~~~~

I've tried Java 7 as well, but did not help. I think the 1.7.0_79 referenced refers to the JDK being used to create the library which I am looking at.

**Comment by amai2012** [comment]
I cannot reproduce with 2.1
